OOP school library: unit tests
blase147/OOP-School-Library pull request #12
Opened 2023-01-20 13:58 UTC by blase147

In this project we;

- Added unit tests for all the methods in all the classes:
  - Book
  - Person
  - Student
  - Teacher
  - Classroom
  - Rental
  - all classes that we created while implementing the Decorator design pattern

2023-01-20 19:01 UTC, Rustamxon7 requested changes
Hello Team,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
_Your project is almost complete!_
_No Linters errors_

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Check the comments under the review._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-20 19:01 UTC, rustam-tolipov commented on spec/person_spec.rb
> +describe Person do
- [ ] Your tests look great. But need to look deeper into this project. So, to test your cases I suggest you create a dynamic date like this: 

```
book = Book.new("Title", "Author")
person = Person.new(24, "Bob")
```

2023-01-20 19:01 UTC, Rustamxon7 commented on spec/student_spec.rb
> +    @student = Student.new 'Title', 'Author'
- [ ] You also need to write tests for positive and negative scenarios. For example, you have parental permission. Or can use services. So you can decide which of them you choose. But you must have written tests for both scenarios. Kindly add them.

2023-01-21 03:26 UTC, roshan-bajgain approved these changes
Hi @blase147, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-21 07:04 UTC, merged